server:
  port: 9000

spring:
  application:
    name: little-stone-api
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/little_stone?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true&useSSL=false&rewriteBatchedStatements=true
    username: root
    password: fushi_00
  data:
    redis:
      host: localhost
      port: 6379
      password: 
      database: 0
      timeout: 10000ms
      lettuce:
        pool:
          max-active: 200
          max-idle: 20
          min-idle: 5
          max-wait: -1ms

security:
  jwt:
    secret-key: 3R6a50IK2yPGNIvtmZTl25Ntiy8RfhLPyR6gWIYQ9Jo=
    expiration: 86400000
    refresh-expiration: 604800000

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
  type-aliases-package: com.fushi.entity


flowable:
  # 全局开关（其他模块用）
  database-schema-update: true
  # 关键：App Engine单独开关（你报错的罪魁祸首）
  app:
    database-schema-update: true
  # 关闭异步执行器，避免启动时额外报错
  async-executor-activate: false
  process:
    async-executor-activate: false