server:
  port: 9000

spring:
  application:
    name: little-stone-api
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/little_stone?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true&useSSL=false&rewriteBatchedStatements=true
    username: root
    password: fushi_00

security:
  jwt:
    secret-key: 3R6a50IK2yPGNIvtmZTl25Ntiy8RfhLPyR6gWIYQ9Jo=
    expiration: 86400000
    refresh-expiration: 604800000

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
  type-aliases-package: com.fushi.entity

